language: java
jdk:
- openjdk8
install: mvn install -DskipTests=true -Dgpg.skip=true
before_deploy:
    - mvn -P fatjar clean package -DskipTests=true -Dproject.finalName=$TRAVIS_TAG
deploy:
  provider: releases
  api_key: 4881f8d9209de4f1ed5f5a69a1d4ec2421e37315
  file: target/$TRAVIS_TAG.jar
  skip_cleanup: true
  on:
    repo: piyo-team-d1/pra1
    all_branches: true
    tags: true
