language: java
jdk:
- openjdk8
install: mvn install -DskipTests=true -Dgpg.skip=true
before_deploy:
    - mvn -P fatjar clean package -DskipTests=true -Dproject.finalName=$TRAVIS_TAG
deploy:
  provider: releases
  api_key: 4881f8d9209de4f1ed5f5a69a1d4ec2421e37315
  file: target/$TRAVIS_TAG.jar
  skip_cleanup: true
  on:
    repo: piyo-team-d1/pra1
    all_branches: true
    tags: true
notifications:
  slack:
    secure: "SBGW6W4uf2LBLr/WrGzH/p+nvrVVyjhvg40tEYuqNBs/kxHbGtk6tILtDMUbfx3uql2YuNP1qV4575ZPpTOP3oxJYsakBGXwV7mKPROqOFCKdPVDhyXfoBdLdEGLvHipjiGCgHTfwaa8ZhyHL6BVnRJd7SFQF3E/4hdG8OFtJ
Zen0KdIoPfSv/00gpn4RayppifJuQ1PEh/OmorGYwztn4iWpLN74jK9yp7Nn+pDcz3hswT/Xoc3ODJt70rEiPCG6FaDjVSOrj50BkLT7PbeE2k8rDTH2IdudcXm/+NJ9GW/QuLzCKeTGM/BT0t3xOydOEIvzL85wBu90SDnD/7hfGwG6r1lA
kXvGUzUHsQYHAKn74ERY2r6f+VqaeIwLuSgXIKsVnXtmSHrqDMJIcbygVjn1wBZfpEyATM6Q/lm5LbnojV4yrvrbH5cnbRbb9Uq9O0svW+2ByQ3lTflgOGcN1DZ+VhJMic7D8Q2r+fGUw2gB7jOaUyOaZ4NG8XUtZex0IimG0j7YOCL5nray
5+cfxpEehU5w243DiO/gEnxuCEBlDiB/0pYVXuMTci32rqLmB5NIs6axXFLSqSYaHWnUgo7yx9SXzfWE/yIFj6m99z3sSo2dg9IgpMMT6nVfPXzRn9nA4AZrkmi/aqGJApy1cgzAmC87ykt0kDZ+K4MIOk="

